name: Deploy to VPS

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: "16.16.0"

            - name: Install dependencies
              run: |
                  cd app
                  npm install

            - name: Build React app
              run: |
                  cd app
                  npm run build
                  mv build build_2

            - name: Transfer sql to VPS
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  source: situations.sql
                  target: /home/ubuntu/docker/portfolio/data

            - name: Transfer build to VPS
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  source: "app/build_2"
                  target: /home/ubuntu/

            - name: Deploy app to VPS
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  script: |
                      cd /var/www/
                      rm -rf build/
                      mv /home/ubuntu/build .
                      cd /home/ubuntu/docker/portfolio
                      docker-compose down -v
                      docker-compose up -d --build
