name: Deploy to VPS

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install dependencies
              run: |
                  cd app
                  npm install

            - name: Build React app
              run: |
                  cd app
                  npm run build
                  zip -r build.zip build

            - name: Transfer sql to VPS
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  source: situations.sql
                  target: /home/ubuntu/docker/portfolio/situations.sql

            - name: Transfer build.zip to VPS
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  source: build.zip
                  target: /home/ubuntu/build.zip

            - name: Deploy app to VPS
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  script: |
                      cd /var/www/html
                      rm -rf build/
                      unzip /home/ubuntu/build.zip
                      cd /home/ubuntu/docker/portfolio
                      docker-compose down -v
                      docker-compose up -d --build
